In [5]:

from pathlib import Path

import time

import json
import glob

PASTA_DADOS = Path(r'C:\Users\jefer\Documents\Ciencia-de-dados\Preco-Imoveis\dados\balneario_camboriu')

now = time.strftime("%Y-%m")
    
padrao_busca = str(PASTA_DADOS / f'balneario_camboriu_vivareal_2026-04_61_70.json')
    
arquivos_json = glob.glob(padrao_busca)

with open(padrao_busca, 'r', encoding='utf-8') as f:
    try:
        conteudo = json.load(f)
        print(f"Total de registros no arquivo final: {len(conteudo)}")
    except Exception as e:
        print(f"Erro ao ler o arquivo final: {e}")

Total de registros no arquivo final: 584

In [6]:
import pandas as pd
dados = pd.DataFrame(conteudo)

In [7]:
dados

,url,titulo,metragem,banheiros,vagas,quartos,valor_imovel,condominio,endereco,iptu,descricao,data_criacao,caracteristicas,fotos,link_maps
0,https://www.vivareal.com.br/imovel/apartamento...,Apartamento com 2 Quartos e 2 banheiros à Vend...,67 m²,2,1,2,R$ 1.060.000,Não informado,"Nacoes, Balneário Camboriú - SC",Não informado,REF 4348 Apartamento com 2 dormitórios sendo 1...,"Anúncio criado em 23 de setembro de 2023, atua...","[67 m², 2 quartos, 2 banheiros, 1 vaga, 1 suíte]",[https://resizedimgs.vivareal.com/img/vr-listi...,https://www.google.com/maps/embed/v1/place?key...
1,https://www.vivareal.com.br/imovel/apartamento...,Apartamento com 2 Quartos e 3 banheiros à Vend...,65 m²,3,1,2,R$ 1.150.000,R$ 450/mês,"Avenida Martin Luther, 188 - Nacoes, Balneário...",R$ 900,Fica no apartamento:- Todos móveis planejados ...,"Anúncio criado em 22 de janeiro de 2026, atual...","[65 m², 2 quartos, 3 banheiros, 1 vaga, 6 anda...",[https://resizedimgs.vivareal.com/img/vr-listi...,https://www.google.com/maps/embed/v1/place?key...
2,https://www.vivareal.com.br/imovel/apartamento...,"Apartamento com 1 Quarto e 1 banheiro à Venda,...",67 m²,1,1,1,R$ 850.000,Isento,"Avenida Brasil, 2801 - Centro, Balneário Cambo...",Isento,Apartamento a venda na quadra mar com com 01 d...,"Anúncio criado em 26 de abril de 2025, atualiz...","[67 m², 1 quarto, 1 banheiro, 1 vaga, Mobiliad...",[https://resizedimgs.vivareal.com/img/vr-listi...,https://www.google.com/maps/embed/v1/place?key...
3,https://www.vivareal.com.br/imovel/apartamento...,Apartamento com 2 Quartos e 2 banheiros à Vend...,66 m²,2,1,2,R$ 1.200.000,Não informado,"Ariribá, Balneário Camboriú - SC",Não informado,Jardim dos Palmares - Excelente Empreendimento...,"Anúncio criado em 21 de maio de 2025, atualiza...","[66 m², 2 quartos, 2 banheiros, 1 vaga, 1 suít...",[https://resizedimgs.vivareal.com/img/vr-listi...,https://www.google.com/maps/embed/v1/place?key...
4,https://www.vivareal.com.br/imovel/apartamento...,Apartamento com 2 Quartos e 1 banheiro à Venda...,70 m²,1,1,2,R$ 890.000,R$ 600/mês,"Centro, Balneário Camboriú - SC",R$ 1.020,"REF 4731 Apartamento muito bem localizado, no ...","Anúncio criado em 24 de abril de 2024, atualiz...","[70 m², 2 quartos, 1 banheiro, 1 vaga, Varanda...",[https://resizedimgs.vivareal.com/img/vr-listi...,https://www.google.com/maps/embed/v1/place?key...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579,https://www.vivareal.com.br/imovel/apartamento...,Apartamento com 2 Quartos e 2 banheiros à Vend...,65 m²,2,1,2,R$ 1.200.000,R$ 600/mês,"Nacoes, Balneário Camboriú - SC",Não informado,Características do apartamento:- 2 Dormitórios...,"Anúncio criado em 17 de novembro de 2025, atua...","[65 m², 2 quartos, 2 banheiros, 1 vaga, 1 suíte]",[https://resizedimgs.vivareal.com/img/vr-listi...,https://www.google.com/maps/embed/v1/place?key...
580,https://www.vivareal.com.br/imovel/apartamento...,Apartamento com 2 Quartos e 2 banheiros à Vend...,62 m²,2,2,2,R$ 1.350.000,Isento,"Avenida do Estado Dalmo Vieira - Centro, Balne...",Não informado,O apartamento no Edifício Icon reflete toda a ...,"Anúncio criado em 8 de janeiro de 2026, atuali...","[62 m², 2 quartos, 2 banheiros, 2 vagas, 10 an...",[https://resizedimgs.vivareal.com/img/vr-listi...,https://www.google.com/maps/embed/v1/place?key...
581,https://www.vivareal.com.br/imovel/apartamento...,Apartamento com 2 Quartos e 2 banheiros à Vend...,64 m²,2,2,2,R$ 1.042.000,R$ 550/mês,"Rua Suíça, 220 - Nacoes, Balneário Camboriú - SC",R$ 1.220,APARTAMENTO DE 2 DOMIRTORIOS - BALNEÁRIO CAMBO...,"Anúncio criado em 30 de outubro de 2025, atual...","[64 m², 2 quartos, 2 banheiros, 2 vagas, 1 suíte]",[https://resizedimgs.vivareal.com/img/vr-listi...,https://www.google.com/maps/embed/v1/place?key...
582,https://www.vivareal.com.br/imovel/apartamento...,Apartamento com 2 Quartos e 1 banheiro à Venda...,63 m²,1,1,2,R$ 940.000,R$ 580/mês,"Rua 2480 - Centro, Balneário Camboriú - SC",Não informado,APARTAMENTO - CENTRO02 Dormitórios Banheiro so...,"Anúncio criado em 28 de outubro de 2025, atual...","[63 m², 2 quartos, 1 banheiro, 1 vaga, 4 andar]",[https://resizedimgs.vivareal.com/img/vr-listi...,https://www.google.com/maps/embed/v1/place?key...
583,https://www.vivareal.com.br/imovel/apartamento...,Apartamento com 2 Quartos e 1 banheiro à Venda...,69 m²,1,1,2,R$ 690.000,R$ 640/mês,"Rua Venezuela, 155 - Nacoes, Balneário Cambori...",Não informado,"Balneário Camboriú 2 dormitórios R$ 650.000,00...","Anúncio criado em 1 de agosto de 2025, atualiz...","[69 m², 2 quartos, 1 banheiro, 1 vaga, Aceita ...",[https://resizedimgs.vivareal.com/img/vr-listi...,https://www.google.com/maps/embed/v1/place?key...

In [8]:
dados.isnull().sum()

url                 0
titulo              0
metragem            0
banheiros           0
vagas               0
quartos             0
valor_imovel        0
condominio          0
endereco            0
iptu                0
descricao          13
data_criacao        0
caracteristicas     0
fotos               0
link_maps           0
dtype: int64

In [5]:
import json
import glob
import os
from pathlib import Path
import time
import os
from dotenv import load_dotenv

load_dotenv()

def consolidar_jsons(fonte, cidade, PASTA_DADOS):
    
    now = time.strftime("%Y-%m")
    
    padrao_busca = str(PASTA_DADOS / f'{cidade}_{fonte}_*.json')
    
    arquivos_json = glob.glob(padrao_busca)
    
    if not arquivos_json:
        print("Nenhum arquivo encontrado com o padrão especificado.")
        return

    dados_consolidados = []
    total_arquivos = len(arquivos_json)

    print(f"Iniciando a união de {total_arquivos} arquivos...")

    for i, caminho in enumerate(arquivos_json, 1):
        nome_base = os.path.basename(caminho)
        with open(caminho, 'r', encoding='utf-8') as f:
            try:
                conteudo = json.load(f)
                # Verifica se o conteúdo é uma lista (padrão do seu scraper)
                if isinstance(conteudo, list):
                    dados_consolidados.extend(conteudo)
                else:
                    dados_consolidados.append(conteudo)
                
                print(f"[{i}/{total_arquivos}] Adicionado: {nome_base} ({len(conteudo)} itens)")
            except Exception as e:
                print(f"Erro ao ler {nome_base}: {e}")

    # 2. Salva o arquivo final consolidado
    nome_final = f'{cidade}_{fonte}_{now}.json'
    
    caminho_final = PASTA_DADOS / nome_final

    try:
        with open(caminho_final, 'w', encoding='utf-8') as f_out:
            json.dump(dados_consolidados, f_out, indent=4, ensure_ascii=False)
        
        # --- VALIDAÇÃO DE SEGURANÇA ---
        tamanho_final = os.path.getsize(caminho_final)
        
        """if tamanho_final > 0 and len(dados_consolidados) > 0:
            print(f"✅ Consolidação concluída: {len(dados_consolidados)} registros.")
            print(f"📦 Arquivo gerado: {nome_final} ({tamanho_final / 1024 / 1024:.2f} MB)")
            
            # 4. Deleta os arquivos anteriores apenas se o final estiver OK
           
            print("🗑️ Removendo arquivos temporários (fatias)...")
            for arquivo_velho in arquivos_json:
                try:
                    os.remove(arquivo_velho)
                    print(f"   Excluído: {os.path.basename(arquivo_velho)}")
                except Exception as e:
                    print(f"   Erro ao excluir {arquivo_velho}: {e}")
        
        
            
            print("✨ Limpeza concluída com sucesso!")
        else:
            print("⚠️ Erro crítico: O arquivo final parece estar vazio. Abortando exclusão.")"""

    except Exception as e:
        print(f"❌ Erro ao salvar arquivo consolidado: {e}")

In [ ]:

import asyncio
import sys
from pathlib import Path
import time

BASE_DIR = Path.cwd().parent

PASTA_DADOS = BASE_DIR / 'dados' / 'jaragua'

consolidar_jsons('vivareal', 'jaragua', PASTA_DADOS)

In [15]:
PASTA_DADOS

WindowsPath('c:/Users/jefer/Documents/Ciencia-de-dados/Preco-Imoveis/dados/balneario_camboriu')

In [3]:
import pandas as pd
import warnings
import logging
import asyncio
from funcoes_limpando_dados_imoveis import (limpar_valor_iptu,
                                            limpar_banheiros, 
                                            limpar_metragem, 
                                            limpar_vagas,  
                                            #limpa_endereco_apply, 
                                            limpar_valor_condominio, 
                                            converter_para_data, 
                                            classificar_tipo_imovel, 
                                            reclassificar_outros, 
                                            preencher_todas_coordenadas,
                                            main_example, 
                                            limpar_valor_venda, 
                                            limpar_quartos, 
                                            pirabeiraba_dona_francisca, 
                                            geocodificar_dataframe,
                                            limpa_endereco_apply_zap, 
                                            limpa_endereco_apply_chave_mao, 
                                            limpa_endereco_apply_olx,)
import time
from datetime import datetime
import json
from pathlib import Path

import asyncio
import sys
from pathlib import Path
import time

cidade = 'joinville'

estado = 'sc'

BASE_DIR = Path.cwd().parent

PASTA_DADOS = BASE_DIR / 'dados' / cidade

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

logger = logging.getLogger(__name__)

warnings.filterwarnings("ignore")

start_time = time.time()

async def limpando_dados_cidades(pd_data, batch, cidade_limpeza = 'joinville', estado_limpeza = 'sc', cidade_localizacao = 'Joinville', estado_localizacao = 'SC',  tipo_async=True,  pais='Brasil'): 
       
    logger.info("Iniciando o processo de limpeza de dados de imóveis...")    
    
    pd_data = pd_data.drop_duplicates(subset=['url'])

    pd_data = pd_data[pd_data['valor_imovel'].notna()]

    pd_data_sem_nulos = pd_data.dropna(thresh=10)

    logger.info(f"Removendo linhas com muitos valores faltantes. Registros restantes: {pd_data_sem_nulos.shape}")

    #endereco_dividido = pd_data_sem_nulos['endereco'].apply(limpa_endereco_apply)

    #pd_data_endereco_dividido = pd.concat([pd_data_sem_nulos, endereco_dividido], axis=1).drop('endereco', axis=1)

    #pd_data_endereco_dividido['bairro'] = pd_data_endereco_dividido['bairro'].apply(pirabeiraba_dona_francisca)

    #logger.info("Coluna 'endereco' dividida em 'rua', 'bairro', 'cidade' e 'estado'...")
    
    pd_data_estado = pd_data_sem_nulos.copy()

    pd_data_estado = pd_data_estado[pd_data_estado['estado'] == estado_limpeza]

    logger.info(f"Removendo linhas com estado diferente de {estado_limpeza}. Registros restantes: {pd_data_estado.shape}")

    pd_data_metragem = pd_data_estado.copy()

    pd_data_metragem['metragem'] = pd_data_metragem['metragem'].apply(limpar_metragem)

    logger.info(f"Coluna 'metragem' limpa. Registros restantes: {pd_data_metragem.shape}")

    pd_data_valor_imovel = pd_data_metragem.copy()

    try:
        pd_data_valor_imovel['valor_venda'] = pd_data_valor_imovel['valor_venda'].apply(limpar_valor_venda)
    except:
        pd_data_valor_imovel['valor_imovel'] = pd_data_valor_imovel['valor_imovel'].apply(limpar_valor_venda)


    logger.info(f"Coluna 'valor_venda' limpa. Registros restantes: {pd_data_valor_imovel.shape}")

    pd_data_valor_condominio = pd_data_valor_imovel.copy()

    pd_data_valor_condominio['condominio'] = pd_data_valor_condominio['condominio'].apply(limpar_valor_condominio)

    logger.info(f"Coluna 'condominio' limpa. Registros restantes: {pd_data_valor_condominio.shape}")

    pd_data_valor_iptu = pd_data_valor_condominio.copy()

    pd_data_valor_iptu['iptu'] = pd_data_valor_iptu['iptu'].apply(limpar_valor_iptu)
    

    logger.info(f"Coluna 'iptu' limpa. Registros restantes: {pd_data_valor_iptu.shape}")

    pd_data_ano_publicacao = pd_data_valor_iptu.copy()

    pd_data_ano_publicacao['data_criacao'] = pd_data_ano_publicacao['data_criacao'].apply(converter_para_data)

    pd_data_ano_publicacao['dias_publicacao'] = (pd.to_datetime(datetime.now().strftime('%Y-%m-%d')) - pd.to_datetime(pd_data_ano_publicacao['data_criacao'], format='%d/%m/%Y')).dt.days
    
    logger.info(f"Coluna 'data_criacao' limpa. Registros restantes: {pd_data_ano_publicacao.shape}")

    pd_data_banheiros = pd_data_ano_publicacao.copy()
    
    pd_data_banheiros['banheiros'] = pd_data_banheiros['banheiros'].apply(limpar_banheiros)

    logger.info(f"Coluna 'banheiros' limpa. Registros restantes: {pd_data_banheiros.shape}")

    pd_data_quartos = pd_data_banheiros.copy()

    pd_data_quartos['quartos'] = pd_data_quartos['quartos'].apply(limpar_quartos)

    logger.info(f"Coluna 'quartos' limpa. Registros restantes: {pd_data_quartos.shape}")

    pd_data_garagem = pd_data_quartos.copy()

    #pd_data_garagem['vagas'] = pd_data_garagem['vagas'].replace('--', 0).astype('int64')

    pd_data_garagem['vagas'] = pd_data_garagem['vagas'].apply(limpar_vagas)

    logger.info(f"Coluna 'vagas' limpa. Registros restantes: {pd_data_garagem.shape}")

    pd_data_tipo_imovel = pd_data_garagem.copy()

    pd_data_tipo_imovel['tipo_imovel'] = pd_data_tipo_imovel['titulo'].apply(classificar_tipo_imovel)

    mask = pd_data_tipo_imovel['tipo_imovel'] == 'outros'

    pd_data_tipo_imovel.loc[mask, 'tipo_imovel'] = (
        pd_data_tipo_imovel.loc[mask, 'descricao']
        .apply(reclassificar_outros)
    )

    logger.info(f"Coluna 'tipo_imovel' classificada. Registros restantes: {pd_data_tipo_imovel.shape}")

    pd_data_long_lat = pd_data_tipo_imovel.copy()
    
    if tipo_async:
        pd_data_lat_log_completo = await preencher_todas_coordenadas(pd_data_long_lat, batch_size=batch, cidade=cidade_localizacao, estado=estado_localizacao, pais=pais)
    else:
        pd_data_lat_log_completo = geocodificar_dataframe(pd_data_long_lat, cidade=cidade_localizacao, estado=estado_localizacao, pais=pais)

    logger.info(f"Todas as coordenadas preenchidas. Registros restantes: {pd_data_lat_log_completo.shape}")

    pd_data_lat_log_completo['preco_por_m2'] = pd_data_lat_log_completo['valor_imovel'] / pd_data_lat_log_completo['metragem']

    logger.info(f'Coluna "preco_por_m2" criada. Registros restantes: {pd_data_lat_log_completo.shape}')

    def classificar_dentro_bairro(grupo):
        p25 = grupo["preco_por_m2"].quantile(0.25)
        p50 = grupo["preco_por_m2"].quantile(0.50)
        p75 = grupo["preco_por_m2"].quantile(0.75)
        
        def faixa(val):
            if val <= p25:
                return "barato"
            elif val <= p50:
                return "medio_baixo"
            if val <= p75:
                return "medio_alto"
            else:
                return "alto_padrao"

        grupo = grupo.copy()
        grupo["faixa"]       = grupo["preco_por_m2"].apply(faixa)
        grupo["p25_bairro"]  = p25
        grupo["p50_bairro"]  = p50
        grupo["p75_bairro"]  = p75
        return grupo

    pd_data_range_bairro_tipo_imovel = pd_data_lat_log_completo.groupby(["bairro", "tipo_imovel"], group_keys=False, ).apply(classificar_dentro_bairro)

    pd_data_range_bairro_tipo_imovel = pd.concat([pd_data_lat_log_completo, pd_data_range_bairro_tipo_imovel[['faixa', 'p25_bairro', 'p50_bairro', 'p75_bairro']]], axis=1)

    logger.info(f"Criando Faixas de preço por bairro e tipo de imóvel classificadas. Registros restantes: {pd_data_range_bairro_tipo_imovel.shape}")

    pd_data_range_bairro_tipo_imovel["desvio_mediana"] = round((pd_data_range_bairro_tipo_imovel["preco_por_m2"] - pd_data_range_bairro_tipo_imovel["p50_bairro"]) / pd_data_range_bairro_tipo_imovel["p50_bairro"],2)

    logger.info(f"Coluna 'desvio_mediana' criada. Registros restantes: {pd_data_range_bairro_tipo_imovel.shape}")
    
    return pd_data_range_bairro_tipo_imovel

In [5]:
def carregar_json(pasta_dados: Path, glob_pattern: str) -> tuple[pd.DataFrame, Path | None]:
    """
    Busca o arquivo mais recente pelo padrão e retorna um DataFrame.
    Retorna DataFrame vazio se não encontrar nenhum arquivo.
    """
    arquivos = list(pasta_dados.glob(glob_pattern))

    if not arquivos:
        logger.warning(f"Nenhum arquivo encontrado para o padrão: {glob_pattern}")
        return pd.DataFrame(), None

    arquivo = max(arquivos, key=lambda f: f.stem.split('_')[-1])
    
    logger.info(f"Arquivo encontrado: {arquivo.name}")

    try:
        with open(arquivo, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return pd.DataFrame(data), arquivo

    except Exception as e:
        logger.error(f"Erro ao carregar {arquivo.name}: {e}")
        return pd.DataFrame(), arquivo

def deletar_arquivo(arquivo: Path | None):
    if arquivo and arquivo.exists():
        arquivo.unlink()
        logger.info(f"Arquivo deletado: {arquivo.name}")

In [6]:
def normalizar_bairros(bairro, mapeamento):
    if not isinstance(bairro, str):
        return bairro
        
    bairro_low = bairro.lower()
    
    for nome_correto, variacoes in mapeamento.items():
        # Verifica se qualquer uma das variações está contida no nome original
        if any(v in bairro_low for v in variacoes):
            return nome_correto
            
    return bairro 

async def limpando_dados(name_arquivo_zap : str, 
         name_arquivo_vivareal: str, 
         name_arquivo_chave_mao: str,
         name_arquivo_olx: str,
         name_arquivo_saida: str,
         pasta_dados : Path, 
         batch: int = 1,
         tipo_async: bool = False,
         cidade_localizacao: str = 'Joinville', 
         cidade_limpeza: str = 'joinville',
         estado_limpeza: str = 'sc', 
         estado_localizacao: str = 'SC',
         pais: str = 'Brasil', 
         MAPA_BAIRROS: dict = None,):
    
    logger.info(f"Iniciando limpeza de dados de imóveis de {cidade_limpeza}...")
    
    logger.info(f"Pasta de dados: {pasta_dados}")

    pasta_dados.mkdir(parents=True, exist_ok=True)

    df_zap, arquivo_zap      = carregar_json(pasta_dados, name_arquivo_zap)
    
    df_vivareal, arquivo_vivareal = carregar_json(pasta_dados,name_arquivo_vivareal)
    
    df_chave_mao, arquivo_chave_mao = carregar_json(pasta_dados,name_arquivo_chave_mao)
    
    df_olx, arquivo_olx = carregar_json(pasta_dados,name_arquivo_olx)

    if not df_zap.empty:
        df_zap['fonte'] = 'zap_imoveis'
    if not df_vivareal.empty:
        df_vivareal['fonte'] = 'viva_real'

    if not df_chave_mao.empty:
        df_chave_mao['fonte'] = 'chave_mao'
    
    if not df_olx.empty:
        df_olx['fonte'] = 'olx'

    if df_zap.empty and df_vivareal.empty and df_chave_mao.empty and df_olx.empty:
        logger.error("Nenhum dado encontrado em nenhuma das fontes — abortando.")
        return
    
    #df_zap_endereco_limpo = df_zap['endereco'].apply(limpa_endereco_apply_zap)
    #df_vivareal_endereco_limpo = df_vivareal['endereco'].apply(limpa_endereco_apply_zap)
    #df_chave_mao_endereco_limpo = df_chave_mao['endereco'].apply(limpa_endereco_apply_chave_mao)
    #df_olx_endereco_limpo = df_olx['endereco'].apply(limpa_endereco_apply_olx)
    
    df_zap_endereco_limpo = df_zap['endereco'].apply(lambda x: limpa_endereco_apply_zap(x, cidade_limpeza, estado_limpeza))
    df_vivareal_endereco_limpo = df_vivareal['endereco'].apply(lambda x: limpa_endereco_apply_zap(x, cidade_limpeza, estado_limpeza))
    df_chave_mao_endereco_limpo = df_chave_mao['endereco'].apply(lambda x: limpa_endereco_apply_chave_mao(x, cidade_limpeza, estado_limpeza))
    df_olx_endereco_limpo = df_olx['endereco'].apply(lambda x: limpa_endereco_apply_olx(x, cidade_limpeza, estado_limpeza))
    
    df_zap_endereco =  pd.concat([df_zap, df_zap_endereco_limpo], axis=1)
    df_vivareal_endereco =  pd.concat([df_vivareal, df_vivareal_endereco_limpo], axis=1)
    df_chave_mao_endereco =  pd.concat([df_chave_mao, df_chave_mao_endereco_limpo], axis=1)
    df_olx_endereco =  pd.concat([df_olx, df_olx_endereco_limpo], axis=1)

    df = pd.concat([df_zap_endereco if not df_zap_endereco.empty else pd.DataFrame(), 
                    df_vivareal_endereco if not df_vivareal_endereco.empty else pd.DataFrame(),
                    df_chave_mao_endereco if not df_chave_mao_endereco.empty else pd.DataFrame(),
                    df_olx_endereco if not df_olx_endereco.empty else pd.DataFrame()], 
                   axis=0, ignore_index=True)
    
    logger.info(f"Total de registros carregados: {len(df)} (zap: {len(df_zap)} | vivareal: {len(df_vivareal)} | chave_mao: {len(df_chave_mao)} | olx: {len(df_olx)})")

    # Limpeza
    df_limpo = await limpando_dados_cidades(df, 
                                        batch = batch, 
                                        cidade_limpeza= cidade_limpeza, 
                                        cidade_localizacao= cidade_localizacao,
                                        tipo_async=tipo_async,
                                        estado_limpeza= estado_limpeza,
                                        estado_localizacao= estado_localizacao, 
                                        pais= pais
                                        )

    # Remove duplicatas
    colunas_dedup = ['valor_imovel', 'rua', 'bairro', 'metragem', 'quartos', 'preco_por_m2', 'banheiros', 'lat', 'lng']
    
    colunas_dedup = [c for c in colunas_dedup if c in df_limpo.columns]  

    antes = len(df_limpo)
    
    df_limpo = df_limpo.drop_duplicates(subset=colunas_dedup, keep='first').reset_index(drop=True)
    
    logger.info(f"Duplicatas removidas: {antes - len(df_limpo)} | Registros finais: {len(df_limpo)}")
    
    if MAPA_BAIRROS:
        df_limpo['bairro'] = df_limpo['bairro'].apply(normalizar_bairros, args=(MAPA_BAIRROS,))
    
    logger.info(f"Coluna 'bairro' corrigida...")
    
    #df_limpo = df_limpo.groupby('bairro').filter(lambda x: len(x) > 1)
    
    return df_limpo

In [14]:
cidade = 'balneario camboriu'
cidade_limpeza = 'balneario camboriu'
estado_limpeza = 'sc'

cidade_localizacao = 'Balneario Camboriu'
estado_localizacao = 'SC'

pais = 'Brasil'

BATCH = 100

PASTA_DADOS  = Path().absolute().parent/ 'dados'/ cidade

MAPA_BAIRROS = {
        'pirabeiraba': ['pirabeiraba', 'dona francisca', 'distrito industrial norte'],
        'distrito industrial': ['distrito industrial', 'zona industrial', 'distrito industrial norte', 'distrito industrial sul'],
        'area rural': ['area rural', 'rural'],
        'vila nova': ['vila nova'],   
        's/b': ['localizacao'],
    }

"""result = await limpando_dados(name_arquivo_zap = f'{cidade}_zap_*.json', 
               name_arquivo_vivareal = f'{cidade}_vivareal_*.json', 
               name_arquivo_chave_mao = f'{cidade}_chave_mao_*.json',
               name_arquivo_olx = f'{cidade}_olx_*.json',
               name_arquivo_saida = f'{cidade}_imoveis_limpo', 
               pasta_dados = PASTA_DADOS, 
               tipo_async = True,
               batch = BATCH, 
               cidade_limpeza=cidade_limpeza,
               cidade_localizacao=cidade_localizacao,
               estado_limpeza=estado_limpeza,
               estado_localizacao=estado_localizacao, 
               MAPA_BAIRROS=MAPA_BAIRROS,
               )

"""

"result = await limpando_dados(name_arquivo_zap = f'{cidade}_zap_*.json', \n               name_arquivo_vivareal = f'{cidade}_vivareal_*.json', \n               name_arquivo_chave_mao = f'{cidade}_chave_mao_*.json',\n               name_arquivo_olx = f'{cidade}_olx_*.json',\n               name_arquivo_saida = f'{cidade}_imoveis_limpo', \n               pasta_dados = PASTA_DADOS, \n               tipo_async = True,\n               batch = BATCH, \n               cidade_limpeza=cidade_limpeza,\n               cidade_localizacao=cidade_localizacao,\n               estado_limpeza=estado_limpeza,\n               estado_localizacao=estado_localizacao, \n               MAPA_BAIRROS=MAPA_BAIRROS,\n               )\n\n"

In [ ]:

cidade = 'balneario_camboriu'
cidade_limpeza = 'balneario camboriu'
estado_limpeza = 'sc'

cidade_localizacao = 'Balneario Camboriu'
estado_localizacao = 'SC'

pais = 'Brasil'
BATCH = 100
tipo_async = True

pasta_dados  = Path().absolute().parent/ 'dados'/ cidade

name_arquivo_zap = f'{cidade}_zap_*.json'
name_arquivo_vivareal = f'{cidade}_vivareal_*.json'
name_arquivo_chave_mao = f'{cidade}_chave_mao_*.json'
name_arquivo_olx = f'{cidade}_olx_*.json'


df_zap, arquivo_zap      = carregar_json(pasta_dados, name_arquivo_zap)
    
df_vivareal, arquivo_vivareal = carregar_json(pasta_dados,name_arquivo_vivareal)
    
df_chave_mao, arquivo_chave_mao = carregar_json(pasta_dados,name_arquivo_chave_mao)
    
df_olx, arquivo_olx = carregar_json(pasta_dados,name_arquivo_olx)

if not df_zap.empty:
    df_zap['fonte'] = 'zap_imoveis'
    df_zap_endereco_limpo = df_zap['endereco'].apply(lambda x: limpa_endereco_apply_zap(x, cidade_limpeza, estado_limpeza))
    df_zap_endereco =  pd.concat([df_zap, df_zap_endereco_limpo], axis=1)


if not df_vivareal.empty:
    df_vivareal['fonte'] = 'viva_real'
    df_vivareal_endereco_limpo = df_vivareal['endereco'].apply(lambda x: limpa_endereco_apply_zap(x, cidade_limpeza, estado_limpeza))
    df_vivareal_endereco =  pd.concat([df_vivareal, df_vivareal_endereco_limpo], axis=1)


if not df_chave_mao.empty:
    df_chave_mao['fonte'] = 'chave_mao'
    df_chave_mao_endereco_limpo = df_chave_mao['endereco'].apply(lambda x: limpa_endereco_apply_chave_mao(x, cidade_limpeza, estado_limpeza))
    df_chave_mao_endereco =  pd.concat([df_chave_mao, df_chave_mao_endereco_limpo], axis=1)


    
if not df_olx.empty:
    df_olx['fonte'] = 'olx'
    df_olx_endereco_limpo = df_olx['endereco'].apply(lambda x: limpa_endereco_apply_olx(x, cidade_limpeza, estado_limpeza))
    df_olx_endereco =  pd.concat([df_olx, df_olx_endereco_limpo], axis=1)



if df_zap.empty and df_vivareal.empty and df_chave_mao.empty and df_olx.empty:
    logger.error("Nenhum dado encontrado em nenhuma das fontes — abortando.")
        
    
    #df_zap_endereco_limpo = df_zap['endereco'].apply(limpa_endereco_apply_zap)
    #df_vivareal_endereco_limpo = df_vivareal['endereco'].apply(limpa_endereco_apply_zap)
    #df_chave_mao_endereco_limpo = df_chave_mao['endereco'].apply(limpa_endereco_apply_chave_mao)
    #df_olx_endereco_limpo = df_olx['endereco'].apply(limpa_endereco_apply_olx)

df = pd.concat([df_zap_endereco if not df_zap_endereco.empty else pd.DataFrame(), 
                    df_vivareal_endereco if not df_vivareal_endereco.empty else pd.DataFrame(),
                    df_chave_mao_endereco if not df_chave_mao_endereco.empty else pd.DataFrame(),
                    df_olx_endereco if not df_olx_endereco.empty else pd.DataFrame()], 
                   axis=0, ignore_index=True)
    
logger.info(f"Total de registros carregados: {len(df)} (zap: {len(df_zap)} | vivareal: {len(df_vivareal)} | chave_mao: {len(df_chave_mao)} | olx: {len(df_olx)})")

    # Limpeza
df_limpo = await limpando_dados_cidades(df, 
                                        batch = BATCH, 
                                        cidade_limpeza= cidade_limpeza, 
                                        cidade_localizacao= cidade_localizacao,
                                        tipo_async=tipo_async,
                                        estado_limpeza= estado_limpeza,
                                        estado_localizacao= estado_localizacao, 
                                        pais= pais
                                        )

    # Remove duplicatas
colunas_dedup = ['valor_imovel', 'rua', 'bairro', 'metragem', 'quartos', 'preco_por_m2', 'banheiros', 'lat', 'lng']
    
colunas_dedup = [c for c in colunas_dedup if c in df_limpo.columns]  

antes = len(df_limpo)
    
df_limpo = df_limpo.drop_duplicates(subset=colunas_dedup, keep='first').reset_index(drop=True)
    
logger.info(f"Duplicatas removidas: {antes - len(df_limpo)} | Registros finais: {len(df_limpo)}")

MAPA_BAIRROS = {
    'centro' : ['centro', 'frente mar centro', 'quadra mar centro', 'quadra mar', '1 quadra do mar', 'rua 57'],
    'das nacoes'  : ['nacoes' , 'das nacoes'],
    'dos estados' : ['estados', 'dos estados'],
    'dos municpios': ['municipios'],
    'dos pioneiros': ['pioneiros', 'dos pioneiros'],
    'jardim iate clube': ['jardim iate clube'],
    'nova esperanca': ['nova esperanca', 'varzea do ranchinho'],
    'praia dos amores': ['praia dos amores'],
    'sao judas tadeu': ['sao judas tadeu'],
    'vila real': ['vila real'],
    'aririba': ['aririba'],
    'taquaras': ['taquaras'],
    'tabuleiro': ['tabuleiro', 'taboleiro'],
    'estaleirinho': ['estaleirinho'],
    'pioneiros': ['pinheiros'],
    's/b' :['localizacao']

}
    
if MAPA_BAIRROS:
    df_limpo['bairro'] = df_limpo['bairro'].apply(normalizar_bairros, args=(MAPA_BAIRROS,))
    
logger.info(f"Coluna 'bairro' corrigida...")
    
result = df_limpo.groupby('bairro').filter(lambda x: len(x) > 1)

2026-04-17 14:22:21,780 - INFO - Arquivo encontrado: balneario_camboriu_zap_2026-04.json
2026-04-17 14:22:23,824 - INFO - Arquivo encontrado: balneario_camboriu_vivareal_2026-04.json
2026-04-17 14:22:25,515 - INFO - Arquivo encontrado: balneario_camboriu_chave_mao_2026-04.json
2026-04-17 14:22:25,658 - INFO - Arquivo encontrado: balneario_camboriu_olx_2026-04.json
2026-04-17 14:22:35,753 - INFO - Total de registros carregados: 24483 (zap: 10573 | vivareal: 10677 | chave_mao: 1483 | olx: 1750)
2026-04-17 14:22:35,756 - INFO - Iniciando o processo de limpeza de dados de imóveis...
2026-04-17 14:22:35,978 - INFO - Removendo linhas com muitos valores faltantes. Registros restantes: (24378, 22)
2026-04-17 14:22:36,036 - INFO - Removendo linhas com estado diferente de sc. Registros restantes: (24370, 22)
2026-04-17 14:22:36,176 - INFO - Coluna 'metragem' limpa. Registros restantes: (24370, 22)
2026-04-17 14:22:36,335 - INFO - Coluna 'valor_venda' limpa. Registros restantes: (24370, 22)
2026-04-17 14:22:36,413 - INFO - Coluna 'condominio' limpa. Registros restantes: (24370, 22)
2026-04-17 14:22:36,480 - INFO - Coluna 'iptu' limpa. Registros restantes: (24370, 22)
2026-04-17 14:22:36,562 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,563 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,565 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,566 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,567 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,567 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,568 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,569 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,570 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,572 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,573 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,574 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,575 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,576 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,577 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,578 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,579 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,580 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,581 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,582 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,583 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,584 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,584 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,585 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,587 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,587 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,589 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,589 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,590 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,591 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,592 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,592 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,593 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,595 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,596 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,597 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,598 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,599 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,600 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,601 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,602 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,603 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,604 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,605 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,606 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,607 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,608 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,609 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,609 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,611 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,612 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,613 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,613 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,614 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,614 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,615 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,616 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,617 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,618 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,619 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,619 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,620 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,621 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,622 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,623 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,624 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,625 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,626 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,627 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,629 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,630 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,630 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,632 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,632 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,633 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,634 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,635 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,636 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,637 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,639 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,640 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,641 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,642 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,643 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,643 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,645 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,645 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,646 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,647 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,648 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,649 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,650 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,651 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,654 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,657 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,659 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,660 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,662 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,662 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,663 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,664 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,666 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,667 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,667 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,668 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,669 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,670 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,672 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,673 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,674 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,674 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,676 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,677 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,679 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,679 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,679 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,680 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,681 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,682 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,683 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,685 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,686 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,687 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,688 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,689 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,690 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,691 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,691 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,692 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,693 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,694 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,695 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,697 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,698 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,699 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,699 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,700 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,700 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,701 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,702 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,704 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,705 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,706 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,707 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,707 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,708 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,710 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,710 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,711 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,712 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,712 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,714 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,715 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,716 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,716 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,717 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,718 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,720 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,720 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,720 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,721 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,722 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,722 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,723 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,725 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,726 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,728 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,729 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,730 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,731 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,732 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,733 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,734 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,734 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,736 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,737 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,738 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,739 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,740 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,741 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,741 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,742 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,743 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,743 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,744 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,745 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,746 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,746 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,748 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,748 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,749 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,750 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,751 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,752 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,752 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,753 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,754 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,758 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,759 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,760 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,761 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,762 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,763 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'
2026-04-17 14:22:36,764 - WARNING - Erro de nome 'NoneType' object has no attribute 'split'

In [19]:
result

,url,titulo,metragem,banheiros,vagas,quartos,valor_imovel,condominio,endereco,iptu,...,dias_publicacao,tipo_imovel,lat,lng,preco_por_m2,faixa,p25_bairro,p50_bairro,p75_bairro,desvio_mediana
0,https://www.zapimoveis.com.br/imovel/venda-apa...,"Apartamento com 1 Quarto à venda, 30m² - Centro",30.0,1,0,1,510000.0,NaN,"Rua 951 - Centro, Balneário Camboriú - SC",NaN,...,302.0,apartamento,-26.992622,-48.632354,17000.000000,medio_baixo,14513.050973,19583.333333,26520.650814,-0.13
1,https://www.zapimoveis.com.br/imovel/venda-apa...,"Apartamento com 1 Quarto à venda, 33m² - Centro",33.0,1,1,1,450000.0,300.0,"Avenida do Estado Dalmo Vieira, 2874 - Centro,...",300.0,...,217.0,apartamento,-26.982494,-48.640141,13636.363636,barato,14513.050973,19583.333333,26520.650814,-0.30
2,https://www.zapimoveis.com.br/imovel/venda-apa...,"Apartamento com 1 Quarto à venda, 34m² - Centro",34.0,1,0,1,690000.0,NaN,"Centro, Balneário Camboriú - SC",NaN,...,632.0,apartamento,-26.992622,-48.632354,20294.117647,medio_alto,14513.050973,19583.333333,26520.650814,0.04
3,https://www.zapimoveis.com.br/imovel/venda-con...,"Conjunto Comercial / Sala à venda, 42m² - Centro",42.0,1,0,0,800000.0,NaN,"Rua 2000 - Centro, Balneário Camboriú - SC",30.0,...,1883.0,comercial,-26.992622,-48.632354,19047.619048,medio_baixo,14463.282996,19047.619048,27591.836735,0.00
4,https://www.zapimoveis.com.br/imovel/venda-apa...,"Apartamento com 1 Quarto à venda, 45m² - Centro",45.0,1,1,1,640000.0,NaN,"Centro, Balneário Camboriú - SC",NaN,...,1387.0,apartamento,-26.992622,-48.632354,14222.222222,barato,14513.050973,19583.333333,26520.650814,-0.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13523,https://sc.olx.com.br/norte-de-santa-catarina/...,Casa 3 Dormitórios (1 Suíte) - Balneário Cambo...,176.0,3,2,3,2500000.0,NaN,"Praia dos Amores, Balneário Camboriú, SC, 8833...",NaN,...,NaN,casa,-24.273056,-53.837734,14204.545455,medio_alto,11134.615385,13888.888889,16333.333333,0.02
13524,https://sc.olx.com.br/norte-de-santa-catarina/...,centro bc otimo preco,56.0,1,1,2,650000.0,NaN,"Centro, Balneário Camboriú, SC, 88330454",NaN,...,NaN,apartamento,-22.017810,-47.824449,11607.142857,barato,14513.050973,19583.333333,26520.650814,-0.41
13525,https://sc.olx.com.br/norte-de-santa-catarina/...,Apartamento mobiliado com 4 dormitórios sendo ...,129.0,3,2,4,3750000.0,NaN,"Centro, Balneário Camboriú, SC, 88330780",NaN,...,NaN,apartamento,-24.277638,-53.825730,29069.767442,alto_padrao,14513.050973,19583.333333,26520.650814,0.48
13526,https://sc.olx.com.br/norte-de-santa-catarina/...,Apartamento no Tierra del Sol Balneário Camboriú,115.0,2,2,3,2500000.0,NaN,"Centro, Balneário Camboriú, SC, 88330789",NaN,...,NaN,apartamento,-7.118806,-34.827997,21739.130435,medio_alto,14513.050973,19583.333333,26520.650814,0.11
13527,https://sc.olx.com.br/norte-de-santa-catarina/...,"Maravilhoso apartamento finamente mobiliado, 4...",147.0,4,3,4,4300000.0,NaN,"Rua 3300, Centro, Balneário Camboriú, SC, 8833...",NaN,...,NaN,apartamento,-26.992622,-48.632354,29251.700680,alto_padrao,14513.050973,19583.333333,26520.650814,0.49

In [20]:
result['bairro'].value_counts()

bairro
centro                9518
dos pioneiros         1082
das nacoes             676
barra sul              467
barra                  284
aririba                277
praia dos amores       263
praia do estaleiro     158
vila real              112
nova esperanca         112
barra norte            102
dos estados             97
sao judas tadeu         91
dos municpios           88
taquaras                87
estaleirinho            54
jardim iate clube       34
tabuleiro                7
frente do mar            6
s/b                      3
localizacao              3
Name: count, dtype: int64

In [22]:
result['estado'].value_counts()

estado
sc    13521
Name: count, dtype: int64

In [28]:
result.to_csv(pasta_dados / 'balneario_camboriu_imoveis_limpo_2026-04.csv', index=False)

In [8]:
import pandas as pd
pd_data = pd.read_csv(PASTA_DADOS / 'joinville_imoveis_limpo_2026-04.csv')

In [ ]:
pd_data['bairro'] = pd_data['bairro'].apply(normalizar_bairros, args=(MAPA_BAIRROS,))

In [12]:
pd_data['bairro'].value_counts()

bairro
america                1300
costa e silva          1245
vila nova              1103
saguacu                1090
anita garibaldi        1078
gloria                  962
floresta                854
bom retiro              732
santo antonio           654
atiradores              551
iririu                  493
pirabeiraba             434
centro                  428
boa vista               374
aventureiro             353
itaum                   313
guanabara               274
joao costa              238
nova brasilia           237
bucarein                231
petropolis              221
paranaguamirim          201
santa catarina          184
boehmerwald             171
jardim sofia            171
jardim iririu           156
comasa                  156
sao marcos              155
adhemar garcia          118
espinheiros             118
parque guarani          117
jarivatuba              116
fatima                  105
jardim paraiso           80
morro do meio            77
itinga                   67
rio bonito               65
ulysses guimaraes        59
distrito industrial      50
profipo                  46
area rural                7
vila cubatao              4
quiriri                   2
s/b                       2
Name: count, dtype: int64

In [ ]:
#pd_data.to_csv(PASTA_DADOS / 'joinville_imoveis_limpo_2026-04.csv', index=False)